from pptx import Presentation
from pptx.util import Inches, Pt


def create_pptx_report(summary: dict, insights: str, output_path: str):
    prs = Presentation()
    # Title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Automated Insight Engine"
    slide.placeholders[1].text = "Generated by the data engine"

    # Summary slide
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Dataset Summary"
    body = slide.shapes.placeholders[1].text_frame
    body.clear()
    body.add_paragraph().text = f"Rows: {summary.get('row_count')}"
    body.add_paragraph().text = f"Columns: {len(summary.get('columns', []))}"
    body.add_paragraph().text = "Missing values:"
    for k, v in summary.get("missing_values", {}).items():
        p = body.add_paragraph()
        p.level = 1
        p.text = f"{k}: {v}"

    # Insights slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "AI Insights"
    body = slide.shapes.placeholders[1].text_frame
    body.clear()
    for line in insights.splitlines():
        p = body.add_paragraph()
        p.text = line

    prs.save(output_path)
